// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (
    user_id,
    name,
    key_hash
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, user_id, name, created_at, updated_at, last_used_at, revoked_at
`

type CreateAPIKeyParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Name    string    `json:"name"`
	KeyHash string    `json:"key_hash"`
}

type CreateAPIKeyRow struct {
	ID         uuid.UUID    `json:"id"`
	UserID     uuid.UUID    `json:"user_id"`
	Name       string       `json:"name"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	LastUsedAt sql.NullTime `json:"last_used_at"`
	RevokedAt  sql.NullTime `json:"revoked_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error) {
	row := q.db.QueryRowContext(ctx, createAPIKey, arg.UserID, arg.Name, arg.KeyHash)
	var i CreateAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const touchAPIKey = `-- name: TouchAPIKey :one
UPDATE api_keys
SET last_used_at = now()
WHERE key_hash = $1
  AND revoked_at IS NULL
RETURNING user_id
`

func (q *Queries) TouchAPIKey(ctx context.Context, keyHash string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, touchAPIKey, keyHash)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}
