// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Name       string             `json:"name"`
	KeyHash    string             `json:"key_hash"`
	CreatedAt  time.Time          `json:"created_at"`
	UpdatedAt  time.Time          `json:"updated_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type Post struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type RefreshToken struct {
	TokenHash string             `json:"token_hash"`
	UserID    uuid.UUID          `json:"user_id"`
	ExpiresAt time.Time          `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt time.Time          `json:"created_at"`
	UpdatedAt time.Time          `json:"updated_at"`
}

type Task struct {
	ID            uuid.UUID `json:"id"`
	Title         string    `json:"title"`
	FrequencyKind string    `json:"frequency_kind"`
	DaysOfWeek    []int16   `json:"days_of_week"`
	PointValue    int32     `json:"point_value"`
	Individual    bool      `json:"individual"`
	IsActive      bool      `json:"is_active"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type TaskAssignment struct {
	TaskID uuid.UUID `json:"task_id"`
	UserID uuid.UUID `json:"user_id"`
}

type TaskCompletion struct {
	ID          uuid.UUID   `json:"id"`
	TaskID      uuid.UUID   `json:"task_id"`
	UserID      uuid.UUID   `json:"user_id"`
	CompletedOn pgtype.Date `json:"completed_on"`
	CreatedAt   time.Time   `json:"created_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	Handle       string    `json:"handle"`
	DisplayName  string    `json:"display_name"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
