// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (user_id, body)
VALUES ($1, $2)
RETURNING id, user_id, body, created_at, updated_at
`

type CreatePostParams struct {
	UserID uuid.UUID `json:"user_id"`
	Body   string    `json:"body"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost, arg.UserID, arg.Body)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReply = `-- name: CreateReply :one
WITH parent AS (
    SELECT id, COALESCE(root_post_id, id) AS root_post_id
    FROM posts
    WHERE id = $1
)
INSERT INTO posts (user_id, body, parent_post_id, root_post_id)
SELECT $2, $3, parent.id, parent.root_post_id
FROM parent
RETURNING id, user_id, body, created_at, updated_at
`

type CreateReplyParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	Body   string    `json:"body"`
}

func (q *Queries) CreateReply(ctx context.Context, arg CreateReplyParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createReply, arg.ID, arg.UserID, arg.Body)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePostForUser = `-- name: DeletePostForUser :exec
DELETE FROM posts
WHERE id = $1 AND user_id = $2
`

type DeletePostForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeletePostForUser(ctx context.Context, arg DeletePostForUserParams) error {
	_, err := q.db.ExecContext(ctx, deletePostForUser, arg.ID, arg.UserID)
	return err
}

const getPost = `-- name: GetPost :one
SELECT id, user_id, body, created_at, updated_at
FROM posts
WHERE id = $1
`

func (q *Queries) GetPost(ctx context.Context, id uuid.UUID) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostForUser = `-- name: GetPostForUser :one
SELECT id, user_id, body, created_at, updated_at
FROM posts
WHERE id = $1 AND user_id = $2
`

type GetPostForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetPostForUser(ctx context.Context, arg GetPostForUserParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPostForUser, arg.ID, arg.UserID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPosts = `-- name: ListPosts :many
SELECT posts.id, posts.user_id, users.display_name, users.handle, posts.body, posts.created_at, posts.updated_at
FROM posts
JOIN users ON users.id = posts.user_id
WHERE posts.parent_post_id IS NULL
ORDER BY posts.created_at DESC, posts.id DESC
LIMIT $1
OFFSET $2
`

type ListPostsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPostsRow struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	DisplayName string    `json:"display_name"`
	Handle      string    `json:"handle"`
	Body        string    `json:"body"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]ListPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsRow{}
	for rows.Next() {
		var i ListPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DisplayName,
			&i.Handle,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByUser = `-- name: ListPostsByUser :many
SELECT posts.id, posts.user_id, users.display_name, users.handle, posts.body, posts.created_at, posts.updated_at
FROM posts
JOIN users ON users.id = posts.user_id
WHERE posts.user_id = $1 AND posts.parent_post_id IS NULL
ORDER BY posts.created_at DESC, posts.id DESC
LIMIT $2
OFFSET $3
`

type ListPostsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListPostsByUserRow struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	DisplayName string    `json:"display_name"`
	Handle      string    `json:"handle"`
	Body        string    `json:"body"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) ListPostsByUser(ctx context.Context, arg ListPostsByUserParams) ([]ListPostsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listPostsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsByUserRow{}
	for rows.Next() {
		var i ListPostsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DisplayName,
			&i.Handle,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostReplies = `-- name: ListPostReplies :many
SELECT posts.id, posts.user_id, users.display_name, users.handle, posts.body, posts.created_at, posts.updated_at
FROM posts
JOIN users ON users.id = posts.user_id
WHERE posts.parent_post_id = $1
ORDER BY posts.created_at ASC, posts.id ASC
LIMIT $2
OFFSET $3
`

type ListPostRepliesParams struct {
	ParentPostID uuid.UUID `json:"parent_post_id"`
	Limit        int32     `json:"limit"`
	Offset       int32     `json:"offset"`
}

type ListPostRepliesRow struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	DisplayName string    `json:"display_name"`
	Handle      string    `json:"handle"`
	Body        string    `json:"body"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) ListPostReplies(ctx context.Context, arg ListPostRepliesParams) ([]ListPostRepliesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPostReplies, arg.ParentPostID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostRepliesRow{}
	for rows.Next() {
		var i ListPostRepliesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DisplayName,
			&i.Handle,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePostForUser = `-- name: UpdatePostForUser :one
UPDATE posts
SET body = $3,
    updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, body, created_at, updated_at
`

type UpdatePostForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	Body   string    `json:"body"`
}

func (q *Queries) UpdatePostForUser(ctx context.Context, arg UpdatePostForUserParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, updatePostForUser, arg.ID, arg.UserID, arg.Body)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
