// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AvailableTasks(ctx context.Context, arg AvailableTasksParams) ([]Task, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateTask(ctx context.Context, title string) (Task, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeletePostForUser(ctx context.Context, arg DeletePostForUserParams) error
	DeleteTask(ctx context.Context, id uuid.UUID) (int64, error)
	GetPost(ctx context.Context, id uuid.UUID) (Post, error)
	GetPostForUser(ctx context.Context, arg GetPostForUserParams) (Post, error)
	GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetTask(ctx context.Context, id uuid.UUID) (Task, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListPosts(ctx context.Context, limit int32) ([]Post, error)
	ListPostsByUser(ctx context.Context, arg ListPostsByUserParams) ([]Post, error)
	ListTasks(ctx context.Context) ([]Task, error)
	RevokeRefreshToken(ctx context.Context, tokenHash string) error
	UpdatePostForUser(ctx context.Context, arg UpdatePostForUserParams) (Post, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
}

var _ Querier = (*Queries)(nil)
