// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const availableTasks = `-- name: AvailableTasks :many
SELECT t.id, t.title, t.frequency_kind, t.days_of_week, t.point_value, t.individual, t.is_active, t.created_at, t.updated_at
FROM tasks t
JOIN task_assignments ta ON ta.task_id = t.id
WHERE ta.user_id = $1
  AND t.is_active = true
  AND (
      t.frequency_kind = 'daily'
      OR (
          t.frequency_kind = 'weekly'
          AND EXTRACT(ISODOW FROM $2::date)::smallint = ANY(t.days_of_week)
      )
  )
  AND NOT EXISTS (
      SELECT 1
      FROM task_completions tc
      WHERE tc.task_id = t.id
        AND tc.user_id = ta.user_id
        AND tc.completed_on = $2::date
  )
`

type AvailableTasksParams struct {
	UserID  uuid.UUID   `json:"user_id"`
	Column2 pgtype.Date `json:"column_2"`
}

func (q *Queries) AvailableTasks(ctx context.Context, arg AvailableTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, availableTasks, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.FrequencyKind,
			&i.DaysOfWeek,
			&i.PointValue,
			&i.Individual,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    id,
    title
) VALUES (
    gen_random_uuid(),
    $1
)
RETURNING
    id,
    title,
    frequency_kind,
    days_of_week,
    point_value,
    individual,
    is_active,
    created_at,
    updated_at
`

func (q *Queries) CreateTask(ctx context.Context, title string) (Task, error) {
	row := q.db.QueryRow(ctx, createTask, title)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.FrequencyKind,
		&i.DaysOfWeek,
		&i.PointValue,
		&i.Individual,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :execrows
DELETE FROM tasks
WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTask, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTask = `-- name: GetTask :one
SELECT
    id,
    title,
    frequency_kind,
    days_of_week,
    point_value,
    individual,
    is_active,
    created_at,
    updated_at
FROM tasks
WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.FrequencyKind,
		&i.DaysOfWeek,
		&i.PointValue,
		&i.Individual,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT
    id,
    title,
    frequency_kind,
    days_of_week,
    point_value,
    individual,
    is_active,
    created_at,
    updated_at
FROM tasks
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.FrequencyKind,
			&i.DaysOfWeek,
			&i.PointValue,
			&i.Individual,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET
    title = COALESCE($1, title)
WHERE id = $2
RETURNING
    id,
    title,
    frequency_kind,
    days_of_week,
    point_value,
    individual,
    is_active,
    created_at,
    updated_at
`

type UpdateTaskParams struct {
	Title pgtype.Text `json:"title"`
	ID    uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask, arg.Title, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.FrequencyKind,
		&i.DaysOfWeek,
		&i.PointValue,
		&i.Individual,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
